-- fn_append_makeup_delivery was written before scheduled_at existed and was
-- never revisited when 20260820120000 added the column. Its INSERT names four
-- columns and omits scheduled_at, so every make-up delivery generated by a skip
-- landed with a null time while the rows create_order wrote all carried one.
-- The order detail timeline renders that null as a bare em dash.
--
-- The slot lives on orders, not on the delivery or its item, so this joins up
-- through order_items to read it.
create or replace function public.fn_append_makeup_delivery()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  v_frequency text;
  v_interval int;
  v_max_date date;
  v_max_seq int;
  v_slot time;
  v_scheduled_date date;
  -- Must match create_order. Combining a date and a time without naming the
  -- zone resolves against the server's UTC and shifts the delivery by 5h30m --
  -- a 07:00 slot would land at 12:30 IST.
  v_zone constant text := 'Asia/Kolkata';
begin
  select oi.subscription_frequency, o.delivery_slot
    into v_frequency, v_slot
  from public.order_items oi
  join public.orders o on o.id = oi.order_id
  where oi.id = new.order_item_id;

  v_interval := case v_frequency
    when 'daily' then 1
    when 'alternate' then 2
    when 'every_3rd' then 3
    else 1
  end;

  select max(scheduled_date), max(sequence_number)
  into v_max_date, v_max_seq
  from public.subscription_deliveries
  where order_item_id = new.order_item_id;

  v_scheduled_date := v_max_date + v_interval;

  insert into public.subscription_deliveries (
    order_item_id, sequence_number, scheduled_date, scheduled_at, status
  )
  values (
    new.order_item_id,
    v_max_seq + 1,
    v_scheduled_date,
    -- Orders placed before delivery slots existed have no slot. Left null on
    -- purpose: inventing 00:00 would promise a midnight delivery, and the UI
    -- already renders an unknown time as an em dash.
    case
      when v_slot is null then null
      else (v_scheduled_date + v_slot) at time zone v_zone
    end,
    'scheduled'
  );

  return new;
end;
$$;

-- Backfill make-up rows already written with a null time. Scoped to rows whose
-- order actually has a slot, so pre-slot orders keep their intended null.
update public.subscription_deliveries sd
set scheduled_at = (sd.scheduled_date + o.delivery_slot) at time zone 'Asia/Kolkata'
from public.order_items oi
join public.orders o on o.id = oi.order_id
where oi.id = sd.order_item_id
  and sd.scheduled_at is null
  and o.delivery_slot is not null;
