-- Serviceability is a property of the address, not of where the phone happens
-- to be at order time. A user at their office ordering to their home, a user
-- ordering for a parent, and a subscription delivery generated by a background
-- job all share the same property: no usable live position exists. These two
-- columns are captured once, at save time, and are authoritative forever after.
--
-- Both nullable, deliberately. Null coordinates mean pincode-tier, which is
-- exactly right for every existing row: nobody was standing at those addresses
-- when they were typed, so their coordinates do not exist and no backfill is
-- possible. addresses.pincode is already not null, so every legacy row has a
-- usable fallback value.
alter table public.addresses
  add column latitude  double precision,
  add column longitude double precision;
